Fix starship skills and proficiencies
sw5e-foundry/sw5e pull request #729
Opened 2023-08-22 21:40 UTC by afwolfe

Fixes the errors thrown when attempting to edit or roll starship skills or proficiencies on SW5e 2.2.2+ as reported in #728

2023-08-22 21:45 UTC, afwolfe commented on module/applications/actor/proficiency-config.mjs
> -
I did not directly modify these (and other) lines, but VS Code picked up on the .prettierrc in the root of the repo and applied them. Should this style be enforced elsewhere or should I revert these additional changes for now?

2023-08-22 21:45 UTC, afwolfe commented on module/applications/actor/proficiency-config.mjs
> +      ? this.document.type === "starship"
This is based on the `title()` method in [module/applications/actor/skill-config.mjs#L39](https://github.com/sw5e-foundry/sw5e/blob/develop/module/applications/actor/skill-config.mjs#L39)

2023-08-22 21:45 UTC, afwolfe commented on static/templates/actors/newActor/starship-sheet.hbs
> +            <li class="proficiency-row skill {{#if skill.value}}proficient{{/if}}" data-property="skills" data-key="{{s}}">
This is based on the Skills section of [static/templates/actors/newActor/parts/swalt-core.hbs#L36](https://github.com/sw5e-foundry/sw5e/blob/develop/static/templates/actors/newActor/parts/swalt-core.hbs#L36)

2023-08-23 16:59 UTC, Ikaguia requested changes
The `prettierrc` changes should be reverted, but other than that everything seems fine

2023-08-23 16:59 UTC, Ikaguia commented on module/applications/actor/proficiency-config.mjs
> -
Alright, so it seems like the `prettierrc` file is no longer used (and we will remove it), instead we are using `eslintrc` with `gulp lint`

2023-08-23 16:59 UTC, Ikaguia commented on module/applications/actor/proficiency-config.mjs
> +      ? this.document.type === "starship"
This looks correct

2023-08-23 16:59 UTC, Ikaguia commented on static/templates/actors/newActor/starship-sheet.hbs
> +            <li class="proficiency-row skill {{#if skill.value}}proficient{{/if}}" data-property="skills" data-key="{{s}}">
This looks correct

2023-08-24 01:28 UTC, afwolfe commented on module/applications/actor/proficiency-config.mjs
> -
I reverted these whitespace changes, and have made 3 separate commits and rebased my changes on top of them:
1. Remove .prettierrc
2. Run `npm run lint:fix` - there were a handful of unrelated fixes that needed applied
3. Fix starship skills and proficiencies

2023-08-25 16:40 UTC, Ikaguia approved these changes
Everything looks correct now

2023-08-25 16:40 UTC, merged